In [1]:
# Importação das bibliotecas a serem utilizadas
import pandas as pd
import numpy as np
import yfinance as yf

Retorno das Ações componentes do IBOV

In [2]:
# Ler arquivo de composição do IBOVESPA retirado do site da B3
ibov_comp = pd.read_excel('IBOVDia_08-04-24.xlsx')

# Adicionar aos códigos '.SA' para ficar no padrão do YFINANCE
ibov_comp['Código'] = ibov_comp['Código'].apply(lambda x: str(x + '.SA')) 

# Ordenar as ações com maior peso no índice (apenas para visualizar)
ibov_comp.sort_values(by='Part. (%)',ascending=False)

      Código          Ação  Qtde. Teórica  Part. (%)
81  VALE3.SA          VALE     4196924316     11.723
60  PETR4.SA     PETROBRAS     4566445852      8.139
47  ITUB4.SA  ITAUUNIBANCO     4801593832      7.352
59  PETR3.SA     PETROBRAS     2379877655      4.346
29  ELET3.SA    ELETROBRAS     1980568384      3.804
..       ...           ...            ...        ...
26  CVCB3.SA    CVC BRASIL      525582771      0.067
36  EZTC3.SA         EZTEC       91514307      0.065
63  PETZ3.SA          PETZ      309729428      0.057
58  PCAR3.SA  P.ACUCAR-CBD      379430826      0.048
17  BHIA3.SA   CASAS BAHIA       94843047      0.030

[86 rows x 4 columns]

In [3]:
# Criação de uma lista contendo todas as ações listadas do índice
tickers = list(ibov_comp['Código'])
tickers

['RRRP3.SA',
 'ALOS3.SA',
 'ALPA4.SA',
 'ABEV3.SA',
 'ARZZ3.SA',
 'ASAI3.SA',
 'AZUL4.SA',
 'B3SA3.SA',
 'BBSE3.SA',
 'BBDC3.SA',
 'BBDC4.SA',
 'BRAP4.SA',
 'BBAS3.SA',
 'BRKM5.SA',
 'BRFS3.SA',
 'BPAC11.SA',
 'CRFB3.SA',
 'BHIA3.SA',
 'CCRO3.SA',
 'CMIG4.SA',
 'CIEL3.SA',
 'COGN3.SA',
 'CPLE6.SA',
 'CSAN3.SA',
 'CPFE3.SA',
 'CMIN3.SA',
 'CVCB3.SA',
 'CYRE3.SA',
 'DXCO3.SA',
 'ELET3.SA',
 'ELET6.SA',
 'EMBR3.SA',
 'ENGI11.SA',
 'ENEV3.SA',
 'EGIE3.SA',
 'EQTL3.SA',
 'EZTC3.SA',
 'FLRY3.SA',
 'GGBR4.SA',
 'GOAU4.SA',
 'NTCO3.SA',
 'SOMA3.SA',
 'HAPV3.SA',
 'HYPE3.SA',
 'IGTI11.SA',
 'IRBR3.SA',
 'ITSA4.SA',
 'ITUB4.SA',
 'JBSS3.SA',
 'KLBN11.SA',
 'RENT3.SA',
 'LREN3.SA',
 'LWSA3.SA',
 'MGLU3.SA',
 'MRFG3.SA',
 'BEEF3.SA',
 'MRVE3.SA',
 'MULT3.SA',
 'PCAR3.SA',
 'PETR3.SA',
 'PETR4.SA',
 'RECV3.SA',
 'PRIO3.SA',
 'PETZ3.SA',
 'RADL3.SA',
 'RAIZ4.SA',
 'RDOR3.SA',
 'RAIL3.SA',
 'SBSP3.SA',
 'SANB11.SA',
 'SMTO3.SA',
 'CSNA3.SA',
 'SLCE3.SA',
 'SUZB3.SA',
 'TAEE11.SA',
 'VIVT3.SA',
 'TIMS3.SA',
 'TOTS3.SA',
 'TRPL4.SA',
 'UGPA3.SA',
 'USIM5.SA',
 'VALE3.SA',
 'VAMO3.SA',
 'VBBR3.SA',
 'WEGE3.SA',
 'YDUQ3.SA']

In [4]:
# Fazer o download das cotações históricas nas datas solicitadas
returns = yf.download(tickers,'2023-12-28','2024-04-11')['Adj Close']

# Fazer o cálculo de variação % diária com base na coluna 'Adj Close'
returns = returns.apply(lambda x: (x / x.shift(1) - 1).fillna(0))

[*********************100%%**********************]  86 of 86 completed

In [5]:
# Visualização da tabela contendo retornos diários de todas as ações
returns.head()

,ABEV3.SA,ALOS3.SA,ALPA4.SA,ARZZ3.SA,ASAI3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,...,TOTS3.SA,TRPL4.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VAMO3.SA,VBBR3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2023-12-28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2024-01-02,-0.001457,-0.030132,-0.080039,-0.035022,-0.037694,-0.081824,-0.019342,-0.011374,-0.011126,-0.019895,...,-0.020481,-0.011321,0.002641,-0.017223,-0.001943,-0.065541,0.009227,-0.015344,-0.009212,-0.046833
2024-01-03,-0.008023,0.000000,0.030075,-0.011884,-0.006144,-0.033333,-0.002823,0.000913,0.000480,0.001134,...,-0.001212,-0.004962,-0.001881,-0.005476,-0.005191,0.022317,0.009578,-0.013113,0.007657,-0.021526
2024-01-04,0.003676,-0.020583,-0.064651,-0.045019,0.020866,-0.026038,-0.029016,-0.010582,-0.013245,-0.013731,...,-0.026092,0.003069,-0.001508,-0.015419,-0.013438,-0.002079,-0.033204,-0.010013,-0.013297,-0.019608
2024-01-05,-0.003663,0.000397,0.045708,0.032675,0.028009,-0.000723,0.018222,0.011986,0.016779,0.021792,...,0.005607,0.000382,0.023028,-0.002237,-0.012827,0.022917,0.018287,-0.018090,-0.010726,0.014634

Retorno do IBOV

In [6]:
# Download das cotações históricas do IBOV
ibov_returns = pd.DataFrame(yf.download('^BVSP','2023-12-28','2024-04-10')['Adj Close'])

# Fazer o cálculo de variação % diária com base na coluna 'Adj Close'
ibov_returns = ibov_returns.apply(lambda x: (x / x.shift(1) - 1).fillna(0))
ibov_returns

[*********************100%%**********************]  1 of 1 completed

            Adj Close
Date
2023-12-28   0.000000
2024-01-02  -0.011089
2024-01-03   0.001032
2024-01-04  -0.012105
2024-01-05   0.006073
...               ...
2024-04-03  -0.001811
2024-04-04   0.000864
2024-04-05  -0.004968
2024-04-08   0.016262
2024-04-09   0.008017

[69 rows x 1 columns]

In [7]:
# Cálculo dos retornos acumulados das ações em Base 100 para comparação
returns_base_100 = ((1 + returns).cumprod())*100
returns_base_100

,ABEV3.SA,ALOS3.SA,ALPA4.SA,ARZZ3.SA,ASAI3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,...,TOTS3.SA,TRPL4.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VAMO3.SA,VBBR3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA
Date,,,,,,,,,,,,,,,,,,,,,
2023-12-28,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2024-01-02,99.854337,96.986820,91.996053,96.497756,96.230604,91.817611,98.065809,98.862604,98.887433,98.010548,...,97.951919,98.867927,100.264052,98.277720,99.805710,93.445880,100.922667,98.465577,99.078824,95.316685
2024-01-03,99.053174,96.986820,94.762848,95.350999,95.639319,88.757026,97.788983,98.952885,98.934937,98.121703,...,97.833186,98.377357,100.075450,97.739504,99.287575,95.531283,101.889281,97.174406,99.837429,93.264941
2024-01-04,99.417335,94.990584,88.636367,91.058422,97.634888,86.445971,94.951506,97.905757,97.624538,96.774347,...,95.280498,98.679244,99.924558,96.232504,97.953375,95.332678,98.506150,96.201354,98.509883,91.436217
2024-01-05,99.053174,95.028250,92.687749,94.033785,100.369551,86.383509,96.681671,99.079256,99.262534,98.883232,...,95.814782,98.716981,102.225580,96.017224,96.696900,97.517378,100.307556,94.461084,97.453261,92.774305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-04,90.823020,89.943502,96.245058,88.377499,102.143385,80.574637,83.576122,103.621856,85.190083,85.631007,...,83.852779,96.792451,108.053962,109.580197,81.697494,80.337640,109.885764,97.186249,104.237479,74.531664
2024-04-05,89.075018,89.717516,94.762848,87.680153,101.478195,80.949406,83.855640,104.059922,84.795383,85.395757,...,83.882462,97.207548,106.753489,106.781487,80.804330,79.443895,111.599294,96.660408,103.936539,74.264048
2024-04-08,88.638022,90.508480,93.181822,87.711141,104.360681,83.073079,84.764077,105.684438,85.255868,85.983879,...,84.357380,97.962261,109.354435,113.024758,85.216024,81.628605,112.697712,96.773082,104.511074,75.111508
2024-04-09,90.021850,90.922788,94.169959,88.021076,108.351812,85.633978,86.580951,106.578828,86.176845,86.513192,...,83.348178,100.188676,109.354435,114.639394,84.647644,86.097322,114.323375,97.374039,106.152605,75.423728
2024-04-10,88.128192,88.286257,90.612650,83.604528,105.247598,79.700188,83.576122,105.136845,84.269113,84.690002,...,82.309293,99.962263,105.950260,111.517758,83.362027,83.316788,112.082601,96.491390,105.058254,72.747544